version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: ${DB_HOST:-db}
      DB_PORT: ${DB_PORT:-5432}
      DB_USER: ${DB_USER:-user}
      DB_PASS: ${DB_PASS:-pass}
      DB_NAME: ${DB_NAME:-carteiradb}
      JWT_SECRET: ${JWT_SECRET:-secret}
      NODE_ENV: ${NODE_ENV:-development}

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASS:-pass}
      POSTGRES_DB: ${DB_NAME:-carteiradb} 
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-user} -d ${DB_NAME:-carteiradb}"]
      interval: 10s
      retries: 5
